import Head from "next/head";
import gsap, { Sine } from "gsap";
import styles from "../styles/Home.module.css";
import { useEffect, useLayoutEffect, useRef } from "react";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
export default function Home() {
  const mainContainer = useRef();
  const firstSection = useRef();
  const textSec = useRef();
  const secondSec = useRef();
  const line1 = useRef(null);
  const line2 = useRef(null);
  const line3 = useRef(null);
  const line4 = useRef(null);
  const line5 = useRef(null);
  const secondSecPara = useRef();

  useEffect(() => {
    gsap.registerPlugin(ScrollTrigger);

    const context = gsap.context(() => {
      ScrollTrigger.config({
        limitCallbacks: true,
        ignoreMobileResize: true,
      });
      if (window.innerWidth <= 800) {
        ScrollTrigger.normalizeScroll(true);
      }
      gsap.to(mainContainer.current, {
        scrollTrigger: {
          trigger: firstSection.current,
          start: "top top",
          end: "bottom bottom",
          // toggleActions: "play reverse play reverse",
        },
        backgroundColor: "black",
        opacity: 1,
      });
      //second sectuon-----
      const textTimeline = gsap.timeline({
        scrollTrigger: {
          trigger: textSec.current,
          start: "top top",
          end: "+=3500",
          scrub: 3,
          pin: textSec.current,
          pinSpacing: true,
          pinReparent: true,
        },
      });
      textTimeline.fromTo(
        [
          line1.current,
          line2.current,
          line3.current,
          line4.current,
          line5.current,
        ],
        {
          y: "100vh",
          opacity: 1,
        },
        {
          y: 0,
          opacity: 1,
          duration: 6,
          stagger: 3,
          ease: Sine.easeOut,
        }
      );
      //third section
      gsap.to(mainContainer.current, {
        scrollTrigger: {
          trigger: secondSec.current,
          start: "top 40%",
          end: "bottom 10%",
          toggleActions: "play reverse play reverse",
        },
        backgroundColor: "white",
      });
      const hiddenWords = Array.from(
        document.querySelectorAll(".second-section p span")
      );
      //shuffling the array so words pop up randomly
      let shuffledWords = hiddenWords
        .map((value) => ({ value, sort: Math.random() }))
        .sort((a, b) => a.sort - b.sort)
        .map(({ value }) => value);
      gsap.to(shuffledWords, {
        scrollTrigger: {
          trigger: secondSec.current,
          start: "top 50%",
          end: "bottom 70%",
          scrub: 1,
        },
        opacity: 1,
        duration: 0.01,
        stagger: 0.01,
      });
    }, [
      line1.current,
      line2.current,
      line3.current,
      line4.current,
      line5.current,
      mainContainer.current,
      firstSection.current,
      textSec.current,
      secondSec.current,
    ]);

    return () => {
      context.revert();
    };
  }, []);
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <div>
        <div ref={mainContainer} className={styles.main}>
          <div ref={firstSection} className={styles.hero}></div>
          <div ref={textSec} className={styles.textSec}>
            <h1 ref={line1}>SHAPING WEB3</h1>
            <h1 ref={line2}>THROUGH</h1>
            <h1 ref={line3}>STORYTELLING,</h1>
            <h1 ref={line4}>EXPERIENCES,</h1>
            <h1 ref={line5}>AND COMMUNITY.</h1>
          </div>
          <div ref={secondSec} className={"second-section " + styles.secondSec}>
            <p ref={secondSecPara}>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
              <span>Lorem </span>
            </p>
          </div>
          <div className={styles.hero}></div>
        </div>
      </div>
    </>
  );
}
